### PR TITLE
Add seo fields

### PR DESCRIPTION
**Pull request by RCheesley**
Pretty minor changes - just adding a component to layouts.

Note that if we want to differentiate between types of pages we'd need to have separate layouts.

### CODE REVIEW

**Comment by kuzmany** [comment]
Looks briliant. We can go to staging with it and marge PR. 
Do you have permission for that?

**Comment by RCheesley** [comment]
Fab, have merged. I've pushed up to staging.

**Comment by kuzmany** [comment]
Just noticed, this plugin destroy our custom page title
Now 
http://staging.mautic.org/mauticamps/atlanta/forum
http://staging.mautic.org/mauticamps/mautic-meetup-curitiba 


I found solution https://octobercms.com/plugin/support/anandpatel-seoextension/how-to-override-seo-extensions-page-title-seocmspage 

But I don't know If it's good idea change all  setup titles.
Maybe exists more elegant solution, but don't know now

**Comment by RCheesley** [comment]
Ok I'll take a look!

**Comment by RCheesley** [comment]
I've flagged this on the GH repo for the current plugin (a fork of the old SEO Extension which was not being maintained) asking how to proceed https://github.com/suresoftware/october-power-seo/issues/3

**Comment by RCheesley** [comment]
@kuzmany did you give this a try for the forum where the title was lost:

function onStart()
{
    $this->layout->components['SeoCmsPage']->seo_title = $dynamicTitle;
}

**Comment by kuzmany** [comment]
I don't like it. 
We have to change it on many places.
But we have no choice

**Comment by RCheesley** [comment]
I think we just need to change it on the group layout, where else does the
dynamic title not work?

**Pull request merged**
